# Generated by Django 4.1.2 on 2022-10-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate_number', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
